image: Ubuntu1804

version: 1.5.2.{build}

branches:
    only:
        - master

environment:
    matrix:
        - GOOS: windows
          GOARCH: amd64
          PREFIX: windows-amd64
          SUFFIX: .exe
        - GOOS: darwin
          GOARCH: amd64
          PREFIX: darwin-amd64
          SUFFIX: 
        - GOOS: linux
          GOARCH: amd64
          PREFIX: linux-amd64
          SUFFIX: 
        - GOOS: freebsd
          GOARCH: amd64
          PREFIX: freebsd-amd64
          SUFFIX: 
        - GOOS: netbsd
          GOARCH: amd64
          PREFIX: netbsd-amd64
          SUFFIX: 
        - GOOS: openbsd
          GOARCH: amd64
          PREFIX: openbsd-amd64
          SUFFIX: 
        - GOOS: dragonfly
          GOARCH: amd64
          PREFIX: dragonfly-amd64
          SUFFIX: 
        - GOOS: solaris
          GOARCH: amd64
          PREFIX: solaris-amd64
          SUFFIX: 
        - GOOS: windows
          GOARCH: 386
          PREFIX: windows-386
          SUFFIX: .exe
        - GOOS: linux
          GOARCH: 386
          PREFIX: linux-386
          SUFFIX: 
        - GOOS: freebsd
          GOARCH: 386
          PREFIX: freebsd-386
          SUFFIX: 
        - GOOS: netbsd
          GOARCH: 386
          PREFIX: netbsd-386
          SUFFIX: 
        - GOOS: openbsd
          GOARCH: 386
          PREFIX: openbsd-386
          SUFFIX: 
        - GOOS: linux
          GOARCH: arm
          GOARM: 5
          PREFIX: linux-armv5
          SUFFIX: 
        - GOOS: linux
          GOARCH: arm
          GOARM: 6
          PREFIX: linux-armv6
          SUFFIX: 
        - GOOS: linux
          GOARCH: arm
          GOARM: 7
          PREFIX: linux-armv7
          SUFFIX: 
        - GOOS: freebsd
          GOARCH: arm
          PREFIX: freebsd-arm
          SUFFIX: 
        - GOOS: netbsd
          GOARCH: arm
          PREFIX: netbsd-arm
          SUFFIX: 
        - GOOS: linux
          GOARCH: arm64
          PREFIX: linux-arm64
          SUFFIX: 
        - GOOS: linux
          GOARCH: ppc64
          PREFIX: linux-ppc64
          SUFFIX: 
        - GOOS: linux
          GOARCH: ppc64le
          PREFIX: linux-ppc64le
          SUFFIX: 
        - GOOS: linux
          GOARCH: mips64
          PREFIX: linux-mips64
          SUFFIX: 
        - GOOS: linux
          GOARCH: mips64le
          PREFIX: linux-mips64le
          SUFFIX: 
        - GOOS: linux
          GOARCH: mips
          PREFIX: linux-mips
          SUFFIX: 
        - GOOS: linux
          GOARCH: mipsle
          PREFIX: linux-mipsle
          SUFFIX: 
        - GOOS: linux
          GOARCH: s390x
          PREFIX: linux-s390x
          SUFFIX: 

clone_depth: 1

# scripts that run after cloning repository
install:
    - set GO111MODULE=on
    - git clone --recursive https://github.com/coredns/coredns.git

# scripts that run before build
before_build:
    - go env
    - go version
    - go get -u github.com/missdeer/block
    - go get -u github.com/coredns/proxy

# custom build scripts
build_script:
    - cp plugin.cfg coredns/plugin.cfg
    - cd coredns
    - make -j 4 coredns
    - cd ..

# scripts that run after build
after_build:
    - mkdir -p "distrib/coredns-$PREFIX" 
    - cp "$APPVEYOR_BUILD_FOLDER/coredns/coredns-$PREFIX$SUFFIX" "distrib/coredns-$PREFIX/coredns$SUFFIX"
    - cd distrib
    - 7z a "coredns-$PREFIX.zip" "coredns-$PREFIX"

artifacts:
    - path: distrib/coredns-$PREFIX.zip
      name: full_package
    - path: distrib/coredns-$PREFIX/coredns*
      name: exe_only
